language: cpp
compiler: 
  - gcc
  - clang
sudo: true
before_script:
  - sudo apt-get install gcc-multilib g++-multilib 
script:
  - mkdir -p build && cd build
  - cmake ../ -DCMAKE_EXE_LINKER_FLAGS="-Wl,--no-undefined" -DUSE_VOICEMGR=0 && make -j3 && rm -rf *
  - cmake ../ -DCMAKE_EXE_LINKER_FLAGS="-Wl,--no-undefined" -DUSE_VOICEMGR=1 && make -j3 && rm -rf *